---
- hosts: app_servers
  become: yes
  vars:
    version: "{{ version }}"
    app_name: "{{ app_name }}"
    nexus_url: "{{ nexus_url }}"
    repo: "{{ repo }}"
    install_dir: /opt/{{ app_name }}

  tasks:
    - name: Ensure Python & pip are installed
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Create install directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: '0755'

    - name: Download artifact from Nexus
      get_url:
        url: "{{ nexus_url }}/repository/{{ repo }}/{{ app_name }}-{{ version }}-py3-none-any.whl"
        dest: "{{ install_dir }}/{{ app_name }}-{{ version }}.whl"
        url_username: "{{ lookup('env','NEXUS_USER') }}"
        url_password: "{{ lookup('env','NEXUS_PASS') }}"


    - name: Install application from wheel
      pip:
        name: "{{ install_dir }}/{{ app_name }}-{{ version }}.whl"
        state: present
